# https://github.com/jdx/mise/releases/tag/v2026.9.7
min_version = '2026.9.7'


[settings]
locked = true
lockfile = true
lockfile_platforms = [
  'linux-arm64',
  'linux-x64',
  'macos-arm64',
]

[settings.python]
compile = false


[task_config]
shell = 'sh -euo pipefail -c'


[tasks.dbt-build]
depends = [
  'dbt-deps',
]
run = 'uv run --no-dev -- dbt build'

[tasks.dbt-compile]
depends = [
  'dbt-deps',
]
run = 'uv run --no-dev -- dbt compile'

[tasks.dbt-deps]
outputs = [
  'dbt_packages',
]
run = 'uv run --no-dev -- dbt deps'
sources = [
  'dependencies.yml',
  'package-lock.yml',
]

[tasks.default]
run = [
  { task = 'dbt-build' },
]

[tasks.dump]
run = 'uv run --no-dev --script -- nppes.py dump'

[tasks.lint]
depends = [
  'dbt-compile',
]
run = """\
if test -n "${CI:-}"; then \
  uv run --group lint -- sqlfluff lint; \
  uv run --only-group lint -- ruff format --diff; \
  uv run --only-group lint -- ruff check; \
else \
  uv run --group lint -- sqlfluff fix --show-lint-violations; \
  uv run --only-group lint -- ruff format; \
  uv run --only-group lint -- ruff check --fix; \
fi; \
uv run --group lint -- mypy"""

[tasks.load]
run = 'uv run --no-dev --script -- nppes.py load'

[tasks.lock]
# required to correctly initialize lockfile when locked = true
env.MISE_LOCKED = '0'
run = [
  'mise install',
  'mise lock',
  'uv lock',
  { task = 'dbt-deps' },
]

[tasks.sync]
run = 'uv sync'

[tasks.upgrade]
# required to correctly initialize lockfile when locked = true
env.MISE_LOCKED = '0'
run = [
  'mise upgrade --local',
  'mise lock',
  'uv lock --upgrade',
  'uv run -- dbt deps --upgrade',
]


[tools]
python = '3.14'
uv = 'latest'
