# https://packaging.python.org/en/latest/guides/writing-pyproject-toml
# https://packaging.python.org/en/latest/specifications/pyproject-toml


[dependency-groups]
dev = [
  { include-group = 'lint' },
]
lint = [
  'mypy >= 2.3.1',
  'ruff >= 0.16.8',
  'sqlfluff [rs] >= 4.3.0',
  'sqlfluff-templater-dbt',
]


[project]
name = 'tuva-provider'
version = '0.1.0'
description = """
A dbt project that transforms messy public provider datasets into usable data for the Tuva \
Project."""
requires-python = '~= 3.14.0'
dependencies = [
  'dbt-core ~= 1.12.0',
  'dbt-duckdb >= 1.11.0',
  'typer >= 0.27.2',
]


[tool.mypy]
allow_redefinition = true
enable_incomplete_feature = [
  'PreciseTupleTypes',
]
exclude_gitignore = true
files = '**/*.py'
install_types = false
native_parser = true
python_version = '3.14'  # https://github.com/python/mypy/issues/19349
strict = true
warn_unreachable = true


[tool.ruff]
line-length = 100

[tool.ruff.format]
preview = true

[tool.ruff.lint]
future-annotations = true
# https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
ignore = [
  'ANN',  # https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
  'COM812',  # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
  'COM819',  # https://docs.astral.sh/ruff/rules/prohibited-trailing-comma/
  'CPY',  # https://docs.astral.sh/ruff/rules/#flake8-copyright-cpy
  'D1',  # https://docs.astral.sh/ruff/rules/#pydocstyle-d
  'D300',  # https://docs.astral.sh/ruff/rules/triple-single-quotes/
  'E111',  # https://docs.astral.sh/ruff/rules/indentation-with-invalid-multiple/
  'E114',  # https://docs.astral.sh/ruff/rules/indentation-with-invalid-multiple-comment/
  'E117',  # https://docs.astral.sh/ruff/rules/over-indented/
  'ERA',  # https://docs.astral.sh/ruff/rules/#eradicate-era
  'FIX002',  # https://docs.astral.sh/ruff/rules/line-contains-todo/
  'ISC001',  # https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/
  'PLR0913',  # https://docs.astral.sh/ruff/rules/too-many-arguments/
  'Q000',  # https://docs.astral.sh/ruff/rules/bad-quotes-inline-string/
  'Q001',  # https://docs.astral.sh/ruff/rules/bad-quotes-multiline-string/
  'Q002',  # https://docs.astral.sh/ruff/rules/bad-quotes-docstring/
  'Q003',  # https://docs.astral.sh/ruff/rules/avoidable-escaped-quote/
  'Q004',  # https://docs.astral.sh/ruff/rules/unnecessary-escaped-quote/
  'S603',  # https://docs.astral.sh/ruff/rules/subprocess-without-shell-equals-true/
  'S606',  # https://docs.astral.sh/ruff/rules/start-process-with-no-shell/
  'S607',  # https://docs.astral.sh/ruff/rules/start-process-with-partial-path/
  'TD002',  # https://docs.astral.sh/ruff/rules/missing-todo-author/
  'TD003',  # https://docs.astral.sh/ruff/rules/missing-todo-link/
  'W191',  # https://docs.astral.sh/ruff/rules/tab-indentation/
]
select = ['ALL']

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
'__init__.py' = [
  'F401',  # https://docs.astral.sh/ruff/rules/unused-import/
]
'tests/**/*.py' = [
  'INP001',  # https://docs.astral.sh/ruff/rules/implicit-namespace-package/
  'S101',  # https://docs.astral.sh/ruff/rules/assert/
]

[tool.ruff.lint.pydocstyle]
convention = 'pep257'


[tool.sqlfluff.core]
dialect = 'duckdb'
encoding = 'utf-8'
exclude_rules = [
  'ST06',
]
ignore_paths = [
  '.venv/',
  'dbt_internal_packages/',
  'dbt_modules/',
  'dbt_packages/',
  'logs/',
  'macros/',
  'target/',
]
large_file_skip_byte_limit = 0
max_line_length = 100
sql_file_exts = '.sql'
templater = 'dbt'
warn_unused_ignores = true

[tool.sqlfluff.indentation]
tab_space_size = 4

[tool.sqlfluff.layout.type.comma]
line_position = 'trailing'
spacing_before = 'touch'

[tool.sqlfluff.rules.aliasing.column]
aliasing = 'explicit'

[tool.sqlfluff.rules.aliasing.expression]
allow_scalar = false

[tool.sqlfluff.rules.aliasing.length]
min_alias_length = 1

[tool.sqlfluff.rules.aliasing.table]
aliasing = 'explicit'

[tool.sqlfluff.rules.ambiguous.column_references]
group_by_and_order_by_style = 'implicit'

[tool.sqlfluff.rules.capitalisation.functions]
capitalisation_policy = 'lower'

[tool.sqlfluff.rules.capitalisation.identifiers]
extended_capitalisation_policy = 'lower'

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = 'lower'

[tool.sqlfluff.rules.capitalisation.literals]
capitalisation_policy = 'lower'

[tool.sqlfluff.templater.dbt]
profiles_dir = '.'


[tool.uv]
package = false
